include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    avoid_implementing_value_types: false
    sort_pub_dependencies: false
analyzer:
  errors:
    unused_import: error
    one_member_abstracts: ignore
    invalid_annotation_target: ignore
    prefer_constructors_over_static_methods: ignore
    use_setters_to_change_properties: ignore

